In [37]:
import pandas as pd

all_ages = pd.read_csv("data/all-ages.csv")
recent_grads = pd.read_csv("data/recent-grads.csv")

In [38]:
all_ages.head()

,Major_code,Major,Major_category,Total,Employed,Employed_full_time_year_round,Unemployed,Unemployment_rate,Median,P25th,P75th
0,1100,GENERAL AGRICULTURE,Agriculture & Natural Resources,128148.0,90245.0,74078.0,2423.0,0.026147,50000.0,34000.0,80000.0
1,1101,AGRICULTURE PRODUCTION AND MANAGEMENT,Agriculture & Natural Resources,95326.0,76865.0,64240.0,2266.0,0.028636,54000.0,36000.0,80000.0
2,1102,AGRICULTURAL ECONOMICS,Agriculture & Natural Resources,33955.0,26321.0,22810.0,821.0,0.030248,63000.0,40000.0,98000.0
3,1103,ANIMAL SCIENCES,Agriculture & Natural Resources,103549.0,81177.0,64937.0,3619.0,0.042679,46000.0,30000.0,72000.0
4,1104,FOOD SCIENCE,Agriculture & Natural Resources,24280.0,17281.0,12722.0,894.0,0.049188,62000.0,38500.0,90000.0

In [39]:
recent_grads.head()

,Rank,Major_code,Major,Major_category,Total,Sample_size,Men,Women,ShareWomen,Employed,...,Part_time,Full_time_year_round,Unemployed,Unemployment_rate,Median,P25th,P75th,College_jobs,Non_college_jobs,Low_wage_jobs
0,1,2419.0,PETROLEUM ENGINEERING,Engineering,2339.0,36.0,2057.0,282.0,0.120564,1976.0,...,270.0,1207.0,37.0,0.018381,110000.0,95000.0,125000.0,1534.0,364.0,193.0
1,2,2416.0,MINING AND MINERAL ENGINEERING,Engineering,756.0,7.0,679.0,77.0,0.101852,640.0,...,170.0,388.0,85.0,0.117241,75000.0,55000.0,90000.0,350.0,257.0,50.0
2,3,2415.0,METALLURGICAL ENGINEERING,Engineering,856.0,3.0,725.0,131.0,0.153037,648.0,...,133.0,340.0,16.0,0.024096,73000.0,50000.0,105000.0,456.0,176.0,0.0
3,4,2417.0,NAVAL ARCHITECTURE AND MARINE ENGINEERING,Engineering,1258.0,16.0,1123.0,135.0,0.107313,758.0,...,150.0,692.0,40.0,0.050125,70000.0,43000.0,80000.0,529.0,102.0,0.0
4,5,2405.0,CHEMICAL ENGINEERING,Engineering,32260.0,289.0,21239.0,11021.0,0.341631,25694.0,...,5180.0,16697.0,1672.0,0.061098,65000.0,50000.0,75000.0,18314.0,4440.0,972.0

In [40]:
all_ages["Major_category"]

0      Agriculture & Natural Resources
1      Agriculture & Natural Resources
2      Agriculture & Natural Resources
3      Agriculture & Natural Resources
4      Agriculture & Natural Resources
                    ...
168                           Business
169                           Business
170                           Business
171          Humanities & Liberal Arts
172          Humanities & Liberal Arts
Name: Major_category, Length: 173, dtype: object

In [41]:
all_ages["Major_category"].unique()

array(['Agriculture & Natural Resources', 'Biology & Life Science',
       'Engineering', 'Humanities & Liberal Arts',
       'Communications & Journalism', 'Computers & Mathematics',
       'Industrial Arts & Consumer Services', 'Education',
       'Law & Public Policy', 'Interdisciplinary', 'Health',
       'Social Science', 'Physical Sciences', nan,
       'Psychology & Social Work', 'Arts', 'Business'], dtype=object)

In [42]:
all_ages["Total"].sum()

np.float64(39806506.0)

🧠 What this function does (big picture)

👉 It calculates the total sum of “Total” column for each Major_category
👉 And stores the result in a dictionary

🧠 Final takeaway
dict() → creates an empty dictionary
Dictionary is used to store:
Key → category
Value → computed total
Your function builds a mapping of category → total sum

In [43]:
def calculate_major_cat_totals(df):
    cats = df['Major_category'].unique()
    counts_dictionary = dict()

    for c in cats:
        major_df = df[df["Major_category"] == c]
        total = major_df["Total"].sum()
        counts_dictionary[c] = total
    return counts_dictionary

In [44]:
aa_cat_counts = dict()
aa_cat_counts = calculate_major_cat_totals(all_ages)
print(aa_cat_counts)

{'Agriculture & Natural Resources': np.float64(632437.0), 'Biology & Life Science': np.float64(1338186.0), 'Engineering': np.float64(3576013.0), 'Humanities & Liberal Arts': np.float64(3738335.0), 'Communications & Journalism': np.float64(1803822.0), 'Computers & Mathematics': np.float64(1781378.0), 'Industrial Arts & Consumer Services': np.float64(1018072.0), 'Education': np.float64(4700118.0), 'Law & Public Policy': np.float64(902926.0), 'Interdisciplinary': np.float64(45199.0), 'Health': np.float64(2950859.0), 'Social Science': np.float64(2654125.0), 'Physical Sciences': np.float64(1013152.0), nan: np.float64(0.0), 'Psychology & Social Work': np.float64(1987278.0), 'Arts': np.float64(1805865.0), 'Business': np.float64(9858741.0)}

In [16]:
rg_cat_counts = dict()
rg_cat_counts = calculate_major_cat_totals(recent_grads)
print(rg_cat_counts)

{'Engineering': np.float64(537583.0), 'Business': np.float64(1302376.0), 'Physical Sciences': np.float64(183363.0), 'Law & Public Policy': np.float64(179107.0), 'Computers & Mathematics': np.float64(299008.0), 'Agriculture & Natural Resources': np.float64(79981.0), 'Industrial Arts & Consumer Services': np.float64(227357.0), 'Arts': np.float64(357130.0), 'Health': np.float64(463230.0), 'Social Science': np.float64(529966.0), nan: np.float64(0.0), 'Biology & Life Science': np.float64(453862.0), 'Education': np.float64(559129.0), 'Humanities & Liberal Arts': np.float64(713468.0), 'Psychology & Social Work': np.float64(481007.0), 'Communications & Journalism': np.float64(392601.0), 'Interdisciplinary': np.float64(12296.0)}

In [45]:
import numpy as np

cat_counts = dict(all_ages.pivot_table(index="Major_category", values="Total", aggfunc=np.sum))
print(cat_counts)

{'Total': Major_category
Agriculture & Natural Resources         632437.0
Arts                                   1805865.0
Biology & Life Science                 1338186.0
Business                               9858741.0
Communications & Journalism            1803822.0
Computers & Mathematics                1781378.0
Education                              4700118.0
Engineering                            3576013.0
Health                                 2950859.0
Humanities & Liberal Arts              3738335.0
Industrial Arts & Consumer Services    1018072.0
Interdisciplinary                        45199.0
Law & Public Policy                     902926.0
Physical Sciences                      1013152.0
Psychology & Social Work               1987278.0
Social Science                         2654125.0
Name: Total, dtype: float64}

/var/folders/4m/dgr_zd0s13d819vvwn8l11n4kjnz1b/T/ipykernel_59163/1616749029.py:3: FutureWarning: The provided callable <function sum at 0x10d006ca0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  cat_counts = dict(all_ages.pivot_table(index="Major_category", values="Total", aggfunc=np.sum))

# List Major_category from 2 DataFrames

In [46]:
all_ages["Major"].unique()

array(['GENERAL AGRICULTURE', 'AGRICULTURE PRODUCTION AND MANAGEMENT',
       'AGRICULTURAL ECONOMICS', 'ANIMAL SCIENCES', 'FOOD SCIENCE',
       'PLANT SCIENCE AND AGRONOMY', 'SOIL SCIENCE',
       'MISCELLANEOUS AGRICULTURE', 'ENVIRONMENTAL SCIENCE', 'FORESTRY',
       'NATURAL RESOURCES MANAGEMENT', 'ARCHITECTURE',
       'AREA ETHNIC AND CIVILIZATION STUDIES', 'COMMUNICATIONS',
       'JOURNALISM', 'MASS MEDIA', 'ADVERTISING AND PUBLIC RELATIONS',
       'COMMUNICATION TECHNOLOGIES', 'COMPUTER AND INFORMATION SYSTEMS',
       'COMPUTER PROGRAMMING AND DATA PROCESSING', 'COMPUTER SCIENCE',
       'INFORMATION SCIENCES',
       'COMPUTER ADMINISTRATION MANAGEMENT AND SECURITY',
       'COMPUTER NETWORKING AND TELECOMMUNICATIONS',
       'COSMETOLOGY SERVICES AND CULINARY ARTS', 'GENERAL EDUCATION',
       'EDUCATIONAL ADMINISTRATION AND SUPERVISION',
       'SCHOOL STUDENT COUNSELING', 'ELEMENTARY EDUCATION',
       'MATHEMATICS TEACHER EDUCATION',
       'PHYSICAL AND HEALTH EDUCATION TEACHING',
       'EARLY CHILDHOOD EDUCATION',
       'SCIENCE AND COMPUTER TEACHER EDUCATION',
       'SECONDARY TEACHER EDUCATION', 'SPECIAL NEEDS EDUCATION',
       'SOCIAL SCIENCE OR HISTORY TEACHER EDUCATION',
       'TEACHER EDUCATION: MULTIPLE LEVELS',
       'LANGUAGE AND DRAMA EDUCATION', 'ART AND MUSIC EDUCATION',
       'MISCELLANEOUS EDUCATION', 'GENERAL ENGINEERING',
       'AEROSPACE ENGINEERING', 'BIOLOGICAL ENGINEERING',
       'ARCHITECTURAL ENGINEERING', 'BIOMEDICAL ENGINEERING',
       'CHEMICAL ENGINEERING', 'CIVIL ENGINEERING',
       'COMPUTER ENGINEERING', 'ELECTRICAL ENGINEERING',
       'ENGINEERING MECHANICS PHYSICS AND SCIENCE',
       'ENVIRONMENTAL ENGINEERING',
       'GEOLOGICAL AND GEOPHYSICAL ENGINEERING',
       'INDUSTRIAL AND MANUFACTURING ENGINEERING',
       'MATERIALS ENGINEERING AND MATERIALS SCIENCE',
       'MECHANICAL ENGINEERING', 'METALLURGICAL ENGINEERING',
       'MINING AND MINERAL ENGINEERING',
       'NAVAL ARCHITECTURE AND MARINE ENGINEERING', 'NUCLEAR ENGINEERING',
       'PETROLEUM ENGINEERING', 'MISCELLANEOUS ENGINEERING',
       'ENGINEERING TECHNOLOGIES',
       'ENGINEERING AND INDUSTRIAL MANAGEMENT',
       'ELECTRICAL ENGINEERING TECHNOLOGY',
       'INDUSTRIAL PRODUCTION TECHNOLOGIES',
       'MECHANICAL ENGINEERING RELATED TECHNOLOGIES',
       'MISCELLANEOUS ENGINEERING TECHNOLOGIES',
       'LINGUISTICS AND COMPARATIVE LANGUAGE AND LITERATURE',
       'FRENCH GERMAN LATIN AND OTHER COMMON FOREIGN LANGUAGE STUDIES',
       'OTHER FOREIGN LANGUAGES', 'FAMILY AND CONSUMER SCIENCES',
       'COURT REPORTING', 'PRE-LAW AND LEGAL STUDIES',
       'ENGLISH LANGUAGE AND LITERATURE', 'COMPOSITION AND RHETORIC',
       'LIBERAL ARTS', 'HUMANITIES', 'LIBRARY SCIENCE', 'BIOLOGY',
       'BIOCHEMICAL SCIENCES', 'BOTANY', 'MOLECULAR BIOLOGY', 'ECOLOGY',
       'GENETICS', 'MICROBIOLOGY', 'PHARMACOLOGY', 'PHYSIOLOGY',
       'ZOOLOGY', 'NEUROSCIENCE', 'MISCELLANEOUS BIOLOGY', 'MATHEMATICS',
       'APPLIED MATHEMATICS', 'STATISTICS AND DECISION SCIENCE',
       'MILITARY TECHNOLOGIES', 'MULTI/INTERDISCIPLINARY STUDIES',
       'INTERCULTURAL AND INTERNATIONAL STUDIES', 'NUTRITION SCIENCES',
       'MATHEMATICS AND COMPUTER SCIENCE',
       'COGNITIVE SCIENCE AND BIOPSYCHOLOGY',
       'INTERDISCIPLINARY SOCIAL SCIENCES',
       'PHYSICAL FITNESS PARKS RECREATION AND LEISURE',
       'PHILOSOPHY AND RELIGIOUS STUDIES',
       'THEOLOGY AND RELIGIOUS VOCATIONS', 'PHYSICAL SCIENCES',
       'ASTRONOMY AND ASTROPHYSICS',
       'ATMOSPHERIC SCIENCES AND METEOROLOGY', 'CHEMISTRY',
       'GEOLOGY AND EARTH SCIENCE', 'GEOSCIENCES', 'OCEANOGRAPHY',
       'PHYSICS', 'MATERIALS SCIENCE',
       'MULTI-DISCIPLINARY OR GENERAL SCIENCE', nan, 'PSYCHOLOGY',
       'EDUCATIONAL PSYCHOLOGY', 'CLINICAL PSYCHOLOGY',
       'COUNSELING PSYCHOLOGY',
       'INDUSTRIAL AND ORGANIZATIONAL PSYCHOLOGY', 'SOCIAL PSYCHOLOGY',
       'MISCELLANEOUS PSYCHOLOGY', 'CRIMINAL JUSTICE AND FIRE PROTECTION',
       'PUBLIC ADMINISTRATION', 'PUBLIC POLICY',
       'HUMAN SERVICES AND COMMUNITY ORGANIZATION', 'SOCIAL WORK',
       'GENERAL SOCIAL SCIENCES', 'ECONOMICS',
       'ANTHROPOLOGY AND ARCHEOLOGY', 'CRIMINOLOGY', 'GEOGRAPHY',
       'INTERNATIONAL RELATIONS', 'POLITICAL SCIENCE AND GOVERNMENT',
       'SOCIOLOGY', 'MISCELLANEOUS SOCIAL SCIENCES',
       'CONSTRUCTION SERVICES',
       'TRANSPORTATION SCIENCES AND TECHNOLOGIES', 'FINE ARTS',
       'DRAMA AND THEATER ARTS', 'MUSIC', 'VISUAL AND PERFORMING ARTS',
       'COMMERCIAL ART AND GRAPHIC DESIGN',
       'FILM VIDEO AND PHOTOGRAPHIC ARTS', 'ART HISTORY AND CRITICISM',
       'STUDIO ARTS', 'MISCELLANEOUS FINE ARTS',
       'GENERAL MEDICAL AND HEALTH SERVICES',
       'COMMUNICATION DISORDERS SCIENCES AND SERVICES',
       'HEALTH AND MEDICAL ADMINISTRATIVE SERVICES',
       'MEDICAL ASSISTING SERVICES', 'MEDICAL TECHNOLOGIES TECHNICIANS',
       'HEALTH AND MEDICAL PREPARATORY PROGRAMS', 'NURSING',
       'PHARMACY PHARMACEUTICAL SCIENCES AND ADMINISTRATION',
       'TREATMENT THERAPY PROFESSIONS', 'COMMUNITY AND PUBLIC HEALTH',
       'MISCELLANEOUS HEALTH MEDICAL PROFESSIONS', 'GENERAL BUSINESS',
       'ACCOUNTING', 'ACTUARIAL SCIENCE',
       'BUSINESS MANAGEMENT AND ADMINISTRATION',
       'OPERATIONS LOGISTICS AND E-COMMERCE', 'BUSINESS ECONOMICS',
       'MARKETING AND MARKETING RESEARCH', 'FINANCE',
       'HUMAN RESOURCES AND PERSONNEL MANAGEMENT',
       'INTERNATIONAL BUSINESS', 'HOSPITALITY MANAGEMENT',
       'MANAGEMENT INFORMATION SYSTEMS AND STATISTICS',
       'MISCELLANEOUS BUSINESS & MEDICAL ADMINISTRATION', 'HISTORY',
       'UNITED STATES HISTORY'], dtype=object)

In [47]:
recent_grads["Major"].unique()

array(['PETROLEUM ENGINEERING', 'MINING AND MINERAL ENGINEERING',
       'METALLURGICAL ENGINEERING',
       'NAVAL ARCHITECTURE AND MARINE ENGINEERING',
       'CHEMICAL ENGINEERING', 'NUCLEAR ENGINEERING', 'ACTUARIAL SCIENCE',
       'ASTRONOMY AND ASTROPHYSICS', 'MECHANICAL ENGINEERING',
       'ELECTRICAL ENGINEERING', 'COMPUTER ENGINEERING',
       'AEROSPACE ENGINEERING', 'BIOMEDICAL ENGINEERING',
       'MATERIALS SCIENCE', 'ENGINEERING MECHANICS PHYSICS AND SCIENCE',
       'BIOLOGICAL ENGINEERING',
       'INDUSTRIAL AND MANUFACTURING ENGINEERING', 'GENERAL ENGINEERING',
       'ARCHITECTURAL ENGINEERING', 'COURT REPORTING', 'COMPUTER SCIENCE',
       'FOOD SCIENCE', 'ELECTRICAL ENGINEERING TECHNOLOGY',
       'MATERIALS ENGINEERING AND MATERIALS SCIENCE',
       'MANAGEMENT INFORMATION SYSTEMS AND STATISTICS',
       'CIVIL ENGINEERING', 'CONSTRUCTION SERVICES',
       'OPERATIONS LOGISTICS AND E-COMMERCE', 'MISCELLANEOUS ENGINEERING',
       'PUBLIC POLICY', 'ENVIRONMENTAL ENGINEERING',
       'ENGINEERING TECHNOLOGIES', 'MISCELLANEOUS FINE ARTS',
       'GEOLOGICAL AND GEOPHYSICAL ENGINEERING', 'NURSING', 'FINANCE',
       'ECONOMICS', 'BUSINESS ECONOMICS',
       'INDUSTRIAL PRODUCTION TECHNOLOGIES', nan, 'ACCOUNTING',
       'MATHEMATICS', 'COMPUTER AND INFORMATION SYSTEMS', 'PHYSICS',
       'MEDICAL TECHNOLOGIES TECHNICIANS', 'INFORMATION SCIENCES',
       'STATISTICS AND DECISION SCIENCE', 'APPLIED MATHEMATICS',
       'PHARMACOLOGY', 'OCEANOGRAPHY',
       'ENGINEERING AND INDUSTRIAL MANAGEMENT',
       'MEDICAL ASSISTING SERVICES', 'MATHEMATICS AND COMPUTER SCIENCE',
       'COMPUTER PROGRAMMING AND DATA PROCESSING',
       'COGNITIVE SCIENCE AND BIOPSYCHOLOGY', 'SCHOOL STUDENT COUNSELING',
       'INTERNATIONAL RELATIONS', 'GENERAL BUSINESS', 'ARCHITECTURE',
       'INTERNATIONAL BUSINESS',
       'PHARMACY PHARMACEUTICAL SCIENCES AND ADMINISTRATION',
       'MOLECULAR BIOLOGY',
       'MISCELLANEOUS BUSINESS & MEDICAL ADMINISTRATION',
       'AGRICULTURE PRODUCTION AND MANAGEMENT', 'GENERAL AGRICULTURE',
       'MISCELLANEOUS ENGINEERING TECHNOLOGIES',
       'MECHANICAL ENGINEERING RELATED TECHNOLOGIES', 'GENETICS',
       'MISCELLANEOUS SOCIAL SCIENCES', 'UNITED STATES HISTORY',
       'INDUSTRIAL AND ORGANIZATIONAL PSYCHOLOGY',
       'AGRICULTURAL ECONOMICS', 'PHYSICAL SCIENCES',
       'MILITARY TECHNOLOGIES', 'CHEMISTRY',
       'BUSINESS MANAGEMENT AND ADMINISTRATION',
       'MARKETING AND MARKETING RESEARCH',
       'POLITICAL SCIENCE AND GOVERNMENT', 'GEOGRAPHY', 'MICROBIOLOGY',
       'COMPUTER ADMINISTRATION MANAGEMENT AND SECURITY',
       'BIOCHEMICAL SCIENCES', 'BOTANY',
       'COMPUTER NETWORKING AND TELECOMMUNICATIONS',
       'GEOLOGY AND EARTH SCIENCE',
       'HUMAN RESOURCES AND PERSONNEL MANAGEMENT',
       'PRE-LAW AND LEGAL STUDIES',
       'MISCELLANEOUS HEALTH MEDICAL PROFESSIONS',
       'PUBLIC ADMINISTRATION', 'GEOSCIENCES', 'SOCIAL PSYCHOLOGY',
       'ENVIRONMENTAL SCIENCE', 'COMMUNICATIONS',
       'CRIMINAL JUSTICE AND FIRE PROTECTION',
       'COMMERCIAL ART AND GRAPHIC DESIGN', 'JOURNALISM',
       'MULTI-DISCIPLINARY OR GENERAL SCIENCE',
       'ADVERTISING AND PUBLIC RELATIONS',
       'AREA ETHNIC AND CIVILIZATION STUDIES', 'SPECIAL NEEDS EDUCATION',
       'PHYSIOLOGY', 'CRIMINOLOGY', 'NUTRITION SCIENCES',
       'HEALTH AND MEDICAL ADMINISTRATIVE SERVICES',
       'COMMUNICATION TECHNOLOGIES',
       'TRANSPORTATION SCIENCES AND TECHNOLOGIES',
       'NATURAL RESOURCES MANAGEMENT', 'NEUROSCIENCE',
       'MULTI/INTERDISCIPLINARY STUDIES',
       'ATMOSPHERIC SCIENCES AND METEOROLOGY', 'FORESTRY', 'SOIL SCIENCE',
       'GENERAL EDUCATION', 'HISTORY',
       'FRENCH GERMAN LATIN AND OTHER COMMON FOREIGN LANGUAGE STUDIES',
       'INTERCULTURAL AND INTERNATIONAL STUDIES',
       'SOCIAL SCIENCE OR HISTORY TEACHER EDUCATION',
       'COMMUNITY AND PUBLIC HEALTH', 'MATHEMATICS TEACHER EDUCATION',
       'EDUCATIONAL ADMINISTRATION AND SUPERVISION',
       'HEALTH AND MEDICAL PREPARATORY PROGRAMS', 'MISCELLANEOUS BIOLOGY',
       'BIOLOGY', 'SOCIOLOGY', 'MASS MEDIA',
       'TREATMENT THERAPY PROFESSIONS', 'HOSPITALITY MANAGEMENT',
       'LANGUAGE AND DRAMA EDUCATION',
       'LINGUISTICS AND COMPARATIVE LANGUAGE AND LITERATURE',
       'MISCELLANEOUS EDUCATION', 'INTERDISCIPLINARY SOCIAL SCIENCES',
       'ECOLOGY', 'SECONDARY TEACHER EDUCATION',
       'GENERAL MEDICAL AND HEALTH SERVICES',
       'PHILOSOPHY AND RELIGIOUS STUDIES', 'ART AND MUSIC EDUCATION',
       'ENGLISH LANGUAGE AND LITERATURE', 'ELEMENTARY EDUCATION',
       'PHYSICAL FITNESS PARKS RECREATION AND LEISURE', 'LIBERAL ARTS',
       'FILM VIDEO AND PHOTOGRAPHIC ARTS', 'GENERAL SOCIAL SCIENCES',
       'PLANT SCIENCE AND AGRONOMY',
       'SCIENCE AND COMPUTER TEACHER EDUCATION', 'PSYCHOLOGY', 'MUSIC',
       'PHYSICAL AND HEALTH EDUCATION TEACHING',
       'ART HISTORY AND CRITICISM', 'FINE ARTS',
       'FAMILY AND CONSUMER SCIENCES', 'SOCIAL WORK', 'ANIMAL SCIENCES',
       'VISUAL AND PERFORMING ARTS', 'TEACHER EDUCATION: MULTIPLE LEVELS',
       'MISCELLANEOUS PSYCHOLOGY',
       'HUMAN SERVICES AND COMMUNITY ORGANIZATION', 'HUMANITIES',
       'THEOLOGY AND RELIGIOUS VOCATIONS', 'STUDIO ARTS',
       'COSMETOLOGY SERVICES AND CULINARY ARTS',
       'MISCELLANEOUS AGRICULTURE', 'ANTHROPOLOGY AND ARCHEOLOGY',
       'COMMUNICATION DISORDERS SCIENCES AND SERVICES',
       'EARLY CHILDHOOD EDUCATION', 'OTHER FOREIGN LANGUAGES',
       'DRAMA AND THEATER ARTS', 'COMPOSITION AND RHETORIC', 'ZOOLOGY',
       'EDUCATIONAL PSYCHOLOGY', 'CLINICAL PSYCHOLOGY',
       'COUNSELING PSYCHOLOGY', 'LIBRARY SCIENCE'], dtype=object)

In [59]:
majors = recent_grads["Major"].unique()

In [60]:
majors

array(['PETROLEUM ENGINEERING', 'MINING AND MINERAL ENGINEERING',
       'METALLURGICAL ENGINEERING',
       'NAVAL ARCHITECTURE AND MARINE ENGINEERING',
       'CHEMICAL ENGINEERING', 'NUCLEAR ENGINEERING', 'ACTUARIAL SCIENCE',
       'ASTRONOMY AND ASTROPHYSICS', 'MECHANICAL ENGINEERING',
       'ELECTRICAL ENGINEERING', 'COMPUTER ENGINEERING',
       'AEROSPACE ENGINEERING', 'BIOMEDICAL ENGINEERING',
       'MATERIALS SCIENCE', 'ENGINEERING MECHANICS PHYSICS AND SCIENCE',
       'BIOLOGICAL ENGINEERING',
       'INDUSTRIAL AND MANUFACTURING ENGINEERING', 'GENERAL ENGINEERING',
       'ARCHITECTURAL ENGINEERING', 'COURT REPORTING', 'COMPUTER SCIENCE',
       'FOOD SCIENCE', 'ELECTRICAL ENGINEERING TECHNOLOGY',
       'MATERIALS ENGINEERING AND MATERIALS SCIENCE',
       'MANAGEMENT INFORMATION SYSTEMS AND STATISTICS',
       'CIVIL ENGINEERING', 'CONSTRUCTION SERVICES',
       'OPERATIONS LOGISTICS AND E-COMMERCE', 'MISCELLANEOUS ENGINEERING',
       'PUBLIC POLICY', 'ENVIRONMENTAL ENGINEERING',
       'ENGINEERING TECHNOLOGIES', 'MISCELLANEOUS FINE ARTS',
       'GEOLOGICAL AND GEOPHYSICAL ENGINEERING', 'NURSING', 'FINANCE',
       'ECONOMICS', 'BUSINESS ECONOMICS',
       'INDUSTRIAL PRODUCTION TECHNOLOGIES', nan, 'ACCOUNTING',
       'MATHEMATICS', 'COMPUTER AND INFORMATION SYSTEMS', 'PHYSICS',
       'MEDICAL TECHNOLOGIES TECHNICIANS', 'INFORMATION SCIENCES',
       'STATISTICS AND DECISION SCIENCE', 'APPLIED MATHEMATICS',
       'PHARMACOLOGY', 'OCEANOGRAPHY',
       'ENGINEERING AND INDUSTRIAL MANAGEMENT',
       'MEDICAL ASSISTING SERVICES', 'MATHEMATICS AND COMPUTER SCIENCE',
       'COMPUTER PROGRAMMING AND DATA PROCESSING',
       'COGNITIVE SCIENCE AND BIOPSYCHOLOGY', 'SCHOOL STUDENT COUNSELING',
       'INTERNATIONAL RELATIONS', 'GENERAL BUSINESS', 'ARCHITECTURE',
       'INTERNATIONAL BUSINESS',
       'PHARMACY PHARMACEUTICAL SCIENCES AND ADMINISTRATION',
       'MOLECULAR BIOLOGY',
       'MISCELLANEOUS BUSINESS & MEDICAL ADMINISTRATION',
       'AGRICULTURE PRODUCTION AND MANAGEMENT', 'GENERAL AGRICULTURE',
       'MISCELLANEOUS ENGINEERING TECHNOLOGIES',
       'MECHANICAL ENGINEERING RELATED TECHNOLOGIES', 'GENETICS',
       'MISCELLANEOUS SOCIAL SCIENCES', 'UNITED STATES HISTORY',
       'INDUSTRIAL AND ORGANIZATIONAL PSYCHOLOGY',
       'AGRICULTURAL ECONOMICS', 'PHYSICAL SCIENCES',
       'MILITARY TECHNOLOGIES', 'CHEMISTRY',
       'BUSINESS MANAGEMENT AND ADMINISTRATION',
       'MARKETING AND MARKETING RESEARCH',
       'POLITICAL SCIENCE AND GOVERNMENT', 'GEOGRAPHY', 'MICROBIOLOGY',
       'COMPUTER ADMINISTRATION MANAGEMENT AND SECURITY',
       'BIOCHEMICAL SCIENCES', 'BOTANY',
       'COMPUTER NETWORKING AND TELECOMMUNICATIONS',
       'GEOLOGY AND EARTH SCIENCE',
       'HUMAN RESOURCES AND PERSONNEL MANAGEMENT',
       'PRE-LAW AND LEGAL STUDIES',
       'MISCELLANEOUS HEALTH MEDICAL PROFESSIONS',
       'PUBLIC ADMINISTRATION', 'GEOSCIENCES', 'SOCIAL PSYCHOLOGY',
       'ENVIRONMENTAL SCIENCE', 'COMMUNICATIONS',
       'CRIMINAL JUSTICE AND FIRE PROTECTION',
       'COMMERCIAL ART AND GRAPHIC DESIGN', 'JOURNALISM',
       'MULTI-DISCIPLINARY OR GENERAL SCIENCE',
       'ADVERTISING AND PUBLIC RELATIONS',
       'AREA ETHNIC AND CIVILIZATION STUDIES', 'SPECIAL NEEDS EDUCATION',
       'PHYSIOLOGY', 'CRIMINOLOGY', 'NUTRITION SCIENCES',
       'HEALTH AND MEDICAL ADMINISTRATIVE SERVICES',
       'COMMUNICATION TECHNOLOGIES',
       'TRANSPORTATION SCIENCES AND TECHNOLOGIES',
       'NATURAL RESOURCES MANAGEMENT', 'NEUROSCIENCE',
       'MULTI/INTERDISCIPLINARY STUDIES',
       'ATMOSPHERIC SCIENCES AND METEOROLOGY', 'FORESTRY', 'SOIL SCIENCE',
       'GENERAL EDUCATION', 'HISTORY',
       'FRENCH GERMAN LATIN AND OTHER COMMON FOREIGN LANGUAGE STUDIES',
       'INTERCULTURAL AND INTERNATIONAL STUDIES',
       'SOCIAL SCIENCE OR HISTORY TEACHER EDUCATION',
       'COMMUNITY AND PUBLIC HEALTH', 'MATHEMATICS TEACHER EDUCATION',
       'EDUCATIONAL ADMINISTRATION AND SUPERVISION',
       'HEALTH AND MEDICAL PREPARATORY PROGRAMS', 'MISCELLANEOUS BIOLOGY',
       'BIOLOGY', 'SOCIOLOGY', 'MASS MEDIA',
       'TREATMENT THERAPY PROFESSIONS', 'HOSPITALITY MANAGEMENT',
       'LANGUAGE AND DRAMA EDUCATION',
       'LINGUISTICS AND COMPARATIVE LANGUAGE AND LITERATURE',
       'MISCELLANEOUS EDUCATION', 'INTERDISCIPLINARY SOCIAL SCIENCES',
       'ECOLOGY', 'SECONDARY TEACHER EDUCATION',
       'GENERAL MEDICAL AND HEALTH SERVICES',
       'PHILOSOPHY AND RELIGIOUS STUDIES', 'ART AND MUSIC EDUCATION',
       'ENGLISH LANGUAGE AND LITERATURE', 'ELEMENTARY EDUCATION',
       'PHYSICAL FITNESS PARKS RECREATION AND LEISURE', 'LIBERAL ARTS',
       'FILM VIDEO AND PHOTOGRAPHIC ARTS', 'GENERAL SOCIAL SCIENCES',
       'PLANT SCIENCE AND AGRONOMY',
       'SCIENCE AND COMPUTER TEACHER EDUCATION', 'PSYCHOLOGY', 'MUSIC',
       'PHYSICAL AND HEALTH EDUCATION TEACHING',
       'ART HISTORY AND CRITICISM', 'FINE ARTS',
       'FAMILY AND CONSUMER SCIENCES', 'SOCIAL WORK', 'ANIMAL SCIENCES',
       'VISUAL AND PERFORMING ARTS', 'TEACHER EDUCATION: MULTIPLE LEVELS',
       'MISCELLANEOUS PSYCHOLOGY',
       'HUMAN SERVICES AND COMMUNITY ORGANIZATION', 'HUMANITIES',
       'THEOLOGY AND RELIGIOUS VOCATIONS', 'STUDIO ARTS',
       'COSMETOLOGY SERVICES AND CULINARY ARTS',
       'MISCELLANEOUS AGRICULTURE', 'ANTHROPOLOGY AND ARCHEOLOGY',
       'COMMUNICATION DISORDERS SCIENCES AND SERVICES',
       'EARLY CHILDHOOD EDUCATION', 'OTHER FOREIGN LANGUAGES',
       'DRAMA AND THEATER ARTS', 'COMPOSITION AND RHETORIC', 'ZOOLOGY',
       'EDUCATIONAL PSYCHOLOGY', 'CLINICAL PSYCHOLOGY',
       'COUNSELING PSYCHOLOGY', 'LIBRARY SCIENCE'], dtype=object)

In [ ]:
rg_unemp_rate = recent_grads['Unemployment_rate'].values
rg_unemp_rate

array([0.01838053, 0.11724138, 0.02409639, 0.05012531, 0.06109771,
       0.17722641, 0.09565217, 0.02116741, 0.05734228, 0.05917385,
       0.06540928, 0.06516208, 0.09208386, 0.02304284, 0.00633434,
       0.08714307, 0.04287554, 0.05982423, 0.06193078, 0.01168969,
       0.06317277, 0.09693146, 0.08755711, 0.0277888 , 0.05823961,
       0.07060957, 0.06002304, 0.0478587 , 0.07439252, 0.1284263 ,
       0.09358857, 0.05503039, 0.089375  , 0.07503828, 0.04486272,
       0.06068636, 0.09909232, 0.09644838, 0.0283081 ,        nan,
       0.06974901, 0.04727714, 0.09346033, 0.0482245 , 0.03698279,
       0.06074144, 0.08627367, 0.09082331, 0.08553157, 0.05699482,
       0.03365166, 0.04250653, 0.        , 0.11398259, 0.07523617,
       0.10757946, 0.09679894, 0.07286147, 0.11333195, 0.09617506,
       0.05552083, 0.08436116, 0.07198297, 0.05003084, 0.01964246,
       0.05253852, 0.05635708, 0.03411765, 0.07307954, 0.04717949,
       0.10878661, 0.07724958, 0.03535353,        nan, 0.0539724 ,
              nan, 0.07221834, 0.06121506, 0.1011746 , 0.11345863,
       0.06677587, 0.09972338, 0.08053138, 0.        , 0.15184981,
       0.07544857, 0.05956965, 0.07196502, 0.08141125, 0.1594906 ,
       0.02437373, 0.0296496 , 0.07858468, 0.07517698, 0.0824522 ,
       0.09679758, 0.06917644, 0.05580682, 0.06796077, 0.06342929,
       0.04150782, 0.0691628 , 0.09724392, 0.06870068, 0.08962626,
       0.11951147, 0.07272452, 0.0666192 , 0.04848168, 0.07086093,
       0.02222856, 0.09672574, 0.        , 0.05735993, 0.09566691,
       0.07556639, 0.08363353, 0.05408294, 0.11214439, 0.01620283,
       0.        , 0.06977971, 0.05854546, 0.07072473, 0.084951  ,
       0.08983683, 0.05982121, 0.06116919, 0.05030643, 0.10443571,
       0.05921195, 0.09230582, 0.05447519, 0.05222898, 0.08210162,
       0.09605168, 0.03863775, 0.08772359, 0.04658571, 0.05146727,
       0.07826759, 0.10577224, 0.10345472, 0.04545454, 0.04726368,
       0.08381087, 0.07595967, 0.0746675 , 0.06029828, 0.0841863 ,
       0.06712819, 0.06882792, 0.0508625 , 0.10219742, 0.03654583,
       0.05190783, 0.03781903, 0.06858407, 0.0626283 , 0.08955224,
       0.05567686, 0.05976676, 0.10279157, 0.047584  , 0.04010498,
       0.10711573, 0.07754113, 0.08174221, 0.04632028, 0.06511219,
       0.1490482 , 0.05362065, 0.10494572])

In [50]:
all_ages_rate = all_ages['Unemployment_rate'].values
all_ages_rate

array([0.02614711, 0.02863606, 0.03024832, 0.0426789 , 0.04918845,
       0.03179089, 0.05086705, 0.03923042, 0.05128983, 0.04256333,
       0.05434128, 0.08599113, 0.06793896, 0.06436031, 0.06191675,
       0.08300476, 0.06721626, 0.08500867, 0.05189124, 0.09026422,
       0.04951866, 0.05284106, 0.07504572, 0.05869412, 0.0549407 ,
       0.04390352, 0.        , 0.10174594, 0.03835916, 0.03298302,
       0.04626696, 0.04935065, 0.04219989, 0.04375568, 0.04714466,
       0.0460132 , 0.03335686, 0.04808029, 0.04097337, 0.03921524,
       0.04768824, 0.04197131, 0.05897406, 0.06904277, 0.07903583,
       0.04626136, 0.05338659, 0.05474383, 0.05050879, 0.04380452,
       0.045732  , 0.        , 0.05149338, 0.05973111, 0.04384386,
       0.04487268, 0.04703161, 0.04030882, 0.06715942, 0.04220535,
       0.05882101, 0.04671121, 0.05465826, 0.05838409, 0.049846  ,
       0.04353327, 0.06019682, 0.08134809, 0.05879254, 0.07237387,
       0.05578485, 0.06651258, 0.0698478 , 0.0686453 , 0.07361495,
       0.06757852, 0.07784376, 0.09484299, 0.05930117, 0.07159753,
       0.03402351, 0.06053708, 0.04891699, 0.04159095, 0.05088075,
       0.0161108 , 0.05113946, 0.0483626 , 0.06889764, 0.04758244,
       0.05293608, 0.05565261, 0.05705405, 0.10179641, 0.07726897,
       0.07433013, 0.06321655, 0.0249004 , 0.04887283, 0.06538345,
       0.046903  , 0.07502033, 0.04250511, 0.03895254, 0.0860215 ,
       0.03672631, 0.05472862, 0.06511053, 0.04279244, 0.05389509,
       0.05209006, 0.02233333, 0.04523112,        nan, 0.06966658,
       0.07563114, 0.10271216, 0.06802139, 0.08362907, 0.08733625,
       0.08200936, 0.05403559, 0.06965492, 0.07921692, 0.07242129,
       0.0593759 , 0.07105693, 0.06131272, 0.07817578, 0.06451917,
       0.06900849, 0.07031327, 0.06937385, 0.0658043 , 0.05439877,
       0.05109708,        nan, 0.04726368, 0.07175327, 0.08027373,
       0.05471919, 0.094658  , 0.07391972, 0.08561891, 0.06391265,
       0.08371383, 0.15614749, 0.05470063, 0.04646718, 0.05700398,
       0.03135685, 0.03620987, 0.07000979, 0.02679682, 0.03435768,
       0.0262916 , 0.0665277 , 0.05357271, 0.05137753, 0.05341467,
       0.05606352, 0.05886534, 0.04326826, 0.06174857, 0.05503289,
       0.04847293, 0.06074809, 0.07135371, 0.05144698, 0.04397714,
       0.05267856, 0.06585101, 0.07349961])

In [52]:
recent_grads_row = recent_grads[recent_grads['Major'] == "PETROLEUM ENGINEERING" ]
recent_grads_row

,Rank,Major_code,Major,Major_category,Total,Sample_size,Men,Women,ShareWomen,Employed,...,Part_time,Full_time_year_round,Unemployed,Unemployment_rate,Median,P25th,P75th,College_jobs,Non_college_jobs,Low_wage_jobs
0,1,2419.0,PETROLEUM ENGINEERING,Engineering,2339.0,36.0,2057.0,282.0,0.120564,1976.0,...,270.0,1207.0,37.0,0.018381,110000.0,95000.0,125000.0,1534.0,364.0,193.0

In [53]:
rg_lower_count = 0

for m in majors:
    recent_grads_row = recent_grads[recent_grads['Major'] == "PETROLEUM ENGINEERING" ]
    all_ages_row = all_ages[all_ages['Major'] == "PETROLEUM ENGINEERING"]

    rg_unemp_rate = recent_grads_row['Unemployment_rate'].values
    aa_unemp_rate = all_ages_row['Unemployment_rate'].values

    if rg_unemp_rate < aa_unemp_rate:
        rg_lower_count += 1

print(rg_lower_count)

172

In [66]:
rg_lower_count = 0

for m in majors:
    recent_grads_row = recent_grads[recent_grads['Major'] == m]
    all_ages_row = all_ages[all_ages['Major'] == m]

    # Skip if any row is empty
    if recent_grads_row.empty or all_ages_row.empty:
        continue

    # Extract single values
    rg_unemp_rate = recent_grads_row['Unemployment_rate'].values[0]
    aa_unemp_rate = all_ages_row['Unemployment_rate'].values[0]

 
    # Compare scalar values
    if rg_unemp_rate < aa_unemp_rate:
        rg_lower_count += 1

print(rg_lower_count)

42