In [3]:
import pandas as pd

food_info =pd.read_csv("data/food_info.csv")
print(food_info)

      NDB_No                   Shrt_Desc  Water_(g)  Energ_Kcal  Protein_(g)  \
0       1001            BUTTER WITH SALT      15.87         717         0.85
1       1002    BUTTER WHIPPED WITH SALT      15.87         717         0.85
2       1003        BUTTER OIL ANHYDROUS       0.24         876         0.28
3       1004                 CHEESE BLUE      42.41         353        21.40
4       1005                CHEESE BRICK      41.11         371        23.24
...      ...                         ...        ...         ...          ...
8613   83110             MACKEREL SALTED      43.00         305        18.50
8614   90240  SCALLOP (BAY&SEA) CKD STMD      70.25         111        20.54
8615   90480                  SYRUP CANE      26.00         269         0.00
8616   90560                   SNAIL RAW      79.20          90        16.10
8617   93600            TURTLE GREEN RAW      78.50          89        19.80

      Lipid_Tot_(g)  Ash_(g)  Carbohydrt_(g)  Fiber_TD_(g)  Sugar_Tot_(g)  \
0             81.11     2.11            0.06           0.0           0.06
1             81.11     2.11            0.06           0.0           0.06
2             99.48     0.00            0.00           0.0           0.00
3             28.74     5.11            2.34           0.0           0.50
4             29.68     3.18            2.79           0.0           0.51
...             ...      ...             ...           ...            ...
8613          25.10    13.40            0.00           0.0           0.00
8614           0.84     2.97            5.41           0.0           0.00
8615           0.00     0.86           73.14           0.0          73.20
8616           1.40     1.30            2.00           0.0           0.00
8617           0.50     1.20            0.00           0.0           0.00

      ...  Vit_A_IU  Vit_A_RAE  Vit_E_(mg)  Vit_D_mcg  Vit_D_IU  Vit_K_(mcg)  \
0     ...    2499.0      684.0        2.32        1.5      60.0          7.0
1     ...    2499.0      684.0        2.32        1.5      60.0          7.0
2     ...    3069.0      840.0        2.80        1.8      73.0          8.6
3     ...     721.0      198.0        0.25        0.5      21.0          2.4
4     ...    1080.0      292.0        0.26        0.5      22.0          2.5
...   ...       ...        ...         ...        ...       ...          ...
8613  ...     157.0       47.0        2.38       25.2    1006.0          7.8
8614  ...       5.0        2.0        0.00        0.0       2.0          0.0
8615  ...       0.0        0.0        0.00        0.0       0.0          0.0
8616  ...     100.0       30.0        5.00        0.0       0.0          0.1
8617  ...     100.0       30.0        0.50        0.0       0.0          0.1

      FA_Sat_(g)  FA_Mono_(g)  FA_Poly_(g)  Cholestrl_(mg)
0         51.368       21.021        3.043           215.0
1         50.489       23.426        3.012           219.0
2         61.924       28.732        3.694           256.0
3         18.669        7.778        0.800            75.0
4         18.764        8.598        0.784            94.0
...          ...          ...          ...             ...
8613       7.148        8.320        6.210            95.0
8614       0.218        0.082        0.222            41.0
8615       0.000        0.000        0.000             0.0
8616       0.361        0.259        0.252            50.0
8617       0.127        0.088        0.170            50.0

[8618 rows x 36 columns]

# Read .CSV

In [2]:
df_alchohol =pd.read_csv("data/world_alcohol.csv")
print(df_alchohol)

      Year       WHO region                   Country Beverage Types  \
0     1986  Western Pacific                  Viet Nam           Wine
1     1986         Americas                   Uruguay          Other
2     1985           Africa              Cte d'Ivoire           Wine
3     1986         Americas                  Colombia           Beer
4     1987         Americas     Saint Kitts and Nevis           Beer
...    ...              ...                       ...            ...
3252  1984           Africa  Central African Republic           Wine
3253  1986  Western Pacific                      Fiji        Spirits
3254  1986           Europe               Switzerland        Spirits
3255  1987  Western Pacific          Papua New Guinea          Other
3256  1986           Africa                 Swaziland          Other

      Display Value
0              0.00
1              0.50
2              1.62
3              4.27
4              1.98
...             ...
3252           0.46
3253           0.05
3254           2.54
3255           0.00
3256           5.15

[3257 rows x 5 columns]

# Columns

In [4]:
print(food_info.columns)

Index(['NDB_No', 'Shrt_Desc', 'Water_(g)', 'Energ_Kcal', 'Protein_(g)',
       'Lipid_Tot_(g)', 'Ash_(g)', 'Carbohydrt_(g)', 'Fiber_TD_(g)',
       'Sugar_Tot_(g)', 'Calcium_(mg)', 'Iron_(mg)', 'Magnesium_(mg)',
       'Phosphorus_(mg)', 'Potassium_(mg)', 'Sodium_(mg)', 'Zinc_(mg)',
       'Copper_(mg)', 'Manganese_(mg)', 'Selenium_(mcg)', 'Vit_C_(mg)',
       'Thiamin_(mg)', 'Riboflavin_(mg)', 'Niacin_(mg)', 'Vit_B6_(mg)',
       'Vit_B12_(mcg)', 'Vit_A_IU', 'Vit_A_RAE', 'Vit_E_(mg)', 'Vit_D_mcg',
       'Vit_D_IU', 'Vit_K_(mcg)', 'FA_Sat_(g)', 'FA_Mono_(g)', 'FA_Poly_(g)',
       'Cholestrl_(mg)'],
      dtype='object')

In [5]:
# diamensions of dataframe
dimensions = food_info.shape
print(dimensions)

(8618, 36)

In [ ]:
# Selecting a single row by label

In [6]:
food_info.loc[0]

NDB_No                         1001
Shrt_Desc          BUTTER WITH SALT
Water_(g)                     15.87
Energ_Kcal                      717
Protein_(g)                    0.85
Lipid_Tot_(g)                 81.11
Ash_(g)                        2.11
Carbohydrt_(g)                 0.06
Fiber_TD_(g)                    0.0
Sugar_Tot_(g)                  0.06
Calcium_(mg)                   24.0
Iron_(mg)                      0.02
Magnesium_(mg)                  2.0
Phosphorus_(mg)                24.0
Potassium_(mg)                 24.0
Sodium_(mg)                   643.0
Zinc_(mg)                      0.09
Copper_(mg)                     0.0
Manganese_(mg)                  0.0
Selenium_(mcg)                  1.0
Vit_C_(mg)                      0.0
Thiamin_(mg)                  0.005
Riboflavin_(mg)               0.034
Niacin_(mg)                   0.042
Vit_B6_(mg)                   0.003
Vit_B12_(mcg)                  0.17
Vit_A_IU                     2499.0
Vit_A_RAE                     684.0
Vit_E_(mg)                     2.32
Vit_D_mcg                       1.5
Vit_D_IU                       60.0
Vit_K_(mcg)                     7.0
FA_Sat_(g)                   51.368
FA_Mono_(g)                  21.021
FA_Poly_(g)                   3.043
Cholestrl_(mg)                215.0
Name: 0, dtype: object

In [9]:
# Selecting multiple rows by label
rows = food_info.loc[[0, 1, 3]]

rows

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0
3,1004,CHEESE BLUE,42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,721.0,198.0,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0

In [10]:
print(food_info.dtypes)

NDB_No               int64
Shrt_Desc           object
Water_(g)          float64
Energ_Kcal           int64
Protein_(g)        float64
Lipid_Tot_(g)      float64
Ash_(g)            float64
Carbohydrt_(g)     float64
Fiber_TD_(g)       float64
Sugar_Tot_(g)      float64
Calcium_(mg)       float64
Iron_(mg)          float64
Magnesium_(mg)     float64
Phosphorus_(mg)    float64
Potassium_(mg)     float64
Sodium_(mg)        float64
Zinc_(mg)          float64
Copper_(mg)        float64
Manganese_(mg)     float64
Selenium_(mcg)     float64
Vit_C_(mg)         float64
Thiamin_(mg)       float64
Riboflavin_(mg)    float64
Niacin_(mg)        float64
Vit_B6_(mg)        float64
Vit_B12_(mcg)      float64
Vit_A_IU           float64
Vit_A_RAE          float64
Vit_E_(mg)         float64
Vit_D_mcg          float64
Vit_D_IU           float64
Vit_K_(mcg)        float64
FA_Sat_(g)         float64
FA_Mono_(g)        float64
FA_Poly_(g)        float64
Cholestrl_(mg)     float64
dtype: object

In [13]:
food_info.loc[103:106]

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
103,1115,WHEY SWEET DRIED,3.19,353,12.93,1.07,8.35,74.46,0.0,74.46,...,30.0,8.0,0.02,0.0,0.0,0.1,0.684,0.297,0.034,6.0
104,1116,YOGURT PLN WHL MILK 8 GRAMS PROT PER 8 OZ,87.90,61,3.47,3.25,0.72,4.66,0.0,4.66,...,99.0,27.0,0.06,0.1,2.0,0.2,2.096,0.893,0.092,13.0
105,1117,YOGURT PLN LOFAT 12 GRAMS PROT PER 8 OZ,85.07,63,5.25,1.55,1.09,7.04,0.0,7.04,...,51.0,14.0,0.03,0.0,1.0,0.2,1.000,0.426,0.044,6.0
106,1118,YOGURT PLN SKIM MILK 13 GRAMS PROT PER 8 OZ,85.23,56,5.73,0.18,1.18,7.68,0.0,7.68,...,7.0,2.0,0.00,0.0,0.0,0.2,0.116,0.049,0.005,2.0

In [16]:
two_five_ten = [2, 15, 100]
food_info.loc[two_five_ten]

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,3069.0,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0
15,1016,CHEESE COTTAGE LOWFAT 1% MILKFAT,82.48,72,12.39,1.02,1.39,2.72,0.0,2.72,...,41.0,11.0,0.01,0.0,0.0,0.1,0.645,0.291,0.031,4.0
100,1112,WHEY ACID FLUID,93.42,24,0.76,0.09,0.61,5.12,0.0,5.12,...,7.0,2.0,0.00,NaN,NaN,0.0,0.057,0.025,0.004,1.0

In [18]:
protein = food_info["Protein_(g)"]
cholestrl = food_info["Cholestrl_(mg)"]

In [19]:
print(protein)

0        0.85
1        0.85
2        0.28
3       21.40
4       23.24
        ...
8613    18.50
8614    20.54
8615     0.00
8616    16.10
8617    19.80
Name: Protein_(g), Length: 8618, dtype: float64

In [20]:
columns = ["Zinc_(mg)", "Copper_(mg)"]
zinc_copper = food_info[columns]

In [ ]:
#directement
zinc_copper = food_info[["Zinc_(mg)", "Copper_(mg)"]]
print(zinc_copper)

      Zinc_(mg)  Copper_(mg)
0          0.09        0.000
1          0.05        0.016
2          0.01        0.001
3          2.66        0.040
4          2.60        0.024
...         ...          ...
8613       1.10        0.100
8614       1.55        0.033
8615       0.19        0.020
8616       1.00        0.400
8617       1.00        0.250

[8618 rows x 2 columns]

In [24]:
selenium_thiamin = food_info[['Shrt_Desc', 'Selenium_(mcg)', 'Thiamin_(mg)']]
print(selenium_thiamin)

                       Shrt_Desc  Selenium_(mcg)  Thiamin_(mg)
0               BUTTER WITH SALT             1.0         0.005
1       BUTTER WHIPPED WITH SALT             1.0         0.005
2           BUTTER OIL ANHYDROUS             0.0         0.001
3                    CHEESE BLUE            14.5         0.029
4                   CHEESE BRICK            14.5         0.014
...                          ...             ...           ...
8613             MACKEREL SALTED            73.4         0.020
8614  SCALLOP (BAY&SEA) CKD STMD            21.7         0.012
8615                  SYRUP CANE             0.7         0.130
8616                   SNAIL RAW            27.4         0.010
8617            TURTLE GREEN RAW            16.8         0.120

[8618 rows x 3 columns]

get all grams

In [25]:
col_names = food_info.columns.tolist()
gram_columns =[]

for c in col_names:
    if c.endswith("(g)"):
        gram_columns.append(c)



gram_df = food_info[gram_columns]
gram_df.head(3)

,Water_(g),Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g)
0,15.87,0.85,81.11,2.11,0.06,0.0,0.06,51.368,21.021,3.043
1,15.87,0.85,81.11,2.11,0.06,0.0,0.06,50.489,23.426,3.012
2,0.24,0.28,99.48,0.00,0.00,0.0,0.00,61.924,28.732,3.694

In [32]:
in_g = "(g)"
in_mg = "(mg)"
in_kcal = "Kcal"
in_mcg = "(mcg)"

In [28]:
def get_spec(spec):
    col_names = food_info.columns.tolist()
    gram_columns =[]

    for c in col_names:
        if c.endswith(spec):
            gram_columns.append(c)



    gram_df = food_info[gram_columns]
    return gram_df.head(3)

In [29]:
get_spec(in_mg)

,Calcium_(mg),Iron_(mg),Magnesium_(mg),Phosphorus_(mg),Potassium_(mg),Sodium_(mg),Zinc_(mg),Copper_(mg),Manganese_(mg),Vit_C_(mg),Thiamin_(mg),Riboflavin_(mg),Niacin_(mg),Vit_B6_(mg),Vit_E_(mg),Cholestrl_(mg)
0,24.0,0.02,2.0,24.0,24.0,643.0,0.09,0.000,0.000,0.0,0.005,0.034,0.042,0.003,2.32,215.0
1,24.0,0.16,2.0,23.0,26.0,659.0,0.05,0.016,0.004,0.0,0.005,0.034,0.042,0.003,2.32,219.0
2,4.0,0.00,0.0,3.0,5.0,2.0,0.01,0.001,0.000,0.0,0.001,0.005,0.003,0.001,2.80,256.0

In [33]:
get_spec(in_mcg)

   Selenium_(mcg)  Vit_B12_(mcg)  Vit_K_(mcg)
0             1.0           0.17          7.0
1             1.0           0.13          7.0
2             0.0           0.01          8.6

In [34]:
# add 100 to Iron value

In [38]:
add_100 = food_info["Iron_(mg)"]
add_100.head(3)

0    0.02
1    0.16
2    0.00
Name: Iron_(mg), dtype: float64

In [39]:
add_100 = food_info["Iron_(mg)"] + 100
add_100

0       100.02
1       100.16
2       100.00
3       100.31
4       100.43
         ...
8613    101.40
8614    100.58
8615    103.60
8616    103.50
8617    101.40
Name: Iron_(mg), Length: 8618, dtype: float64

In [40]:
mult_2 = food_info["Iron_(mg)"] * 2
mult_2

0       0.04
1       0.32
2       0.00
3       0.62
4       0.86
        ...
8613    2.80
8614    1.16
8615    7.20
8616    7.00
8617    2.80
Name: Iron_(mg), Length: 8618, dtype: float64

In [41]:
max_calories = food_info["Energ_Kcal"].max()
print(max_calories)

902

In [44]:
normalized_protien = food_info["Protein_(g)"] / food_info["Protein_(g)"].max()
normalized_fat = food_info["Lipid_Tot_(g)"] / food_info["Lipid_Tot_(g)"].max()

In [45]:
print(normalized_fat)

0       0.8111
1       0.8111
2       0.9948
3       0.2874
4       0.2968
         ...
8613    0.2510
8614    0.0084
8615    0.0000
8616    0.0140
8617    0.0050
Name: Lipid_Tot_(g), Length: 8618, dtype: float64

In [47]:
normalized_protien.head(3)

0    0.009624
1    0.009624
2    0.003170
Name: Protein_(g), dtype: float64

# Sort Data Frame

In [49]:
food_info.sort_values("Energ_Kcal")

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
4207,14074,BEVERAGES ZEVIA COLA CAFFEINE FREE,98.87,0,0.0,0.0,0.01,1.13,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.0
4378,14439,WATER BTLD NON-CARBONATED NAYA,100.00,0,0.0,0.0,0.10,0.00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4377,14438,WATER BTLD NON-CARBONATED CRYSTAL GEYSER,100.00,0,0.0,0.0,0.10,0.00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4239,14121,CARBONATED BEV CLUB SODA,99.90,0,0.0,0.0,0.10,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.0
4357,14412,WATER TAP WELL,99.90,0,0.0,0.0,0.10,0.00,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704,4592,FISH OIL MENHADEN FULLY HYDR,0.00,902,0.0,100.0,0.00,0.00,0.0,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,95.600,0.000,0.000,500.0
702,4590,FISH OIL HERRING,0.00,902,0.0,100.0,0.00,0.00,0.0,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,21.290,56.564,15.604,766.0
701,4589,FISH OIL COD LIVER,0.00,902,0.0,100.0,0.00,0.00,0.0,NaN,...,100000.0,30000.0,NaN,250.0,10000.0,NaN,22.608,46.711,22.541,570.0
706,4594,FISH OIL SARDINE,0.00,902,0.0,100.0,0.00,0.00,0.0,NaN,...,0.0,0.0,NaN,8.3,332.0,NaN,29.892,33.841,31.867,710.0
611,4002,LARD,0.00,902,0.0,100.0,0.00,0.00,0.0,0.0,...,0.0,0.0,0.6,2.5,102.0,0.0,39.200,45.100,11.200,95.0

In [55]:
food_info.sort_values("Energ_Kcal", ascending= False)

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
610,4001,FAT BEEF TALLOW,0.00,902,0.0,100.0,0.00,0.00,0.0,0.0,...,0.0,0.0,2.7,0.7,28.0,0.0,49.800,41.800,4.000,109.0
704,4592,FISH OIL MENHADEN FULLY HYDR,0.00,902,0.0,100.0,0.00,0.00,0.0,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,95.600,0.000,0.000,500.0
611,4002,LARD,0.00,902,0.0,100.0,0.00,0.00,0.0,0.0,...,0.0,0.0,0.6,2.5,102.0,0.0,39.200,45.100,11.200,95.0
706,4594,FISH OIL SARDINE,0.00,902,0.0,100.0,0.00,0.00,0.0,NaN,...,0.0,0.0,NaN,8.3,332.0,NaN,29.892,33.841,31.867,710.0
705,4593,FISH OIL SALMON,0.00,902,0.0,100.0,0.00,0.00,0.0,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,19.872,29.037,40.324,485.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4392,14537,CARBONATED BEV LOCAL OTHR THAN COLA OR PEP W/ ...,99.80,0,0.0,0.0,0.10,0.10,0.0,NaN,...,0.0,0.0,NaN,NaN,NaN,NaN,0.000,0.000,0.000,0.0
4239,14121,CARBONATED BEV CLUB SODA,99.90,0,0.0,0.0,0.10,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.0
4207,14074,BEVERAGES ZEVIA COLA CAFFEINE FREE,98.87,0,0.0,0.0,0.01,1.13,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.000,0.0
4270,14166,CARBONATED BEV LO CAL COLA OR PEPR W/ NA SACC ...,99.80,0,0.0,0.0,0.10,0.10,0.0,0.0,...,0.0,0.0,0.0,NaN,NaN,0.0,0.000,0.000,0.000,0.0
4282,14201,COFFEE BREWED FROM GROUNDS PREP W/ TAP H2O DEC...,99.30,0,0.1,0.0,0.10,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.1,0.002,0.000,0.002,0.0